import React from 'react'

export default class Screen extends React.Component {

  renderSeatColor(i) {
    if (this.props.selects.some((element) => element === i)) {
      return ("yellow");
    } else {
      return ("red");
    }
  }

  renderSeat(i) {
    const str = this.props.reserved_seat + "";
    if (str.split("/").some((element) => element === i)) {
      return (
        <button
        className="seat"
        style={{background: "gray"}}
        >
          {i}
        </button>
      );
    } else {
      return (
        <Seat
          number={i}
          onClick={() => this.props.onClick(i)}
          color={this.renderSeatColor(i)}
        />
      );
    }
  }
    
  nullSeat() {
    return (
      <button className="null-seat"　disabled>
      </button>
    );
  }

  render() {

    if (this.props.screen == 1) {
      return (
        <div>
          <div className="screen">SCREEN1</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.nullSeat("A3")}
              {this.nullSeat("A4")}
              {this.nullSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
              {this.nullSeat("A16")}
              {this.nullSeat("A17")}
              {this.nullSeat("A18")}
              {this.nullSeat("A19")}
              {this.nullSeat("A20")}
            </div>
            <div className="board-row">
              {this.renderSeat("B1")}
              {this.renderSeat("B2")}
              {this.renderSeat("B3")}
              {this.nullSeat("B4")}
              {this.nullSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
              {this.nullSeat("B16")}
              {this.nullSeat("B17")}
              {this.renderSeat("B18")}
              {this.renderSeat("B19")}
              {this.renderSeat("B20")}
            </div>
            <div className="board-row">
              {this.renderSeat("C1")}
              {this.renderSeat("C2")}
              {this.renderSeat("C3")}
              {this.nullSeat("C4")}
              {this.nullSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
              {this.nullSeat("C16")}
              {this.nullSeat("C17")}
              {this.renderSeat("C18")}
              {this.renderSeat("C19")}
              {this.renderSeat("C20")}
            </div>
            <div className="board-row">
              {this.renderSeat("D1")}
              {this.renderSeat("D2")}
              {this.renderSeat("D3")}
              {this.nullSeat("D4")}
              {this.nullSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
              {this.nullSeat("D16")}
              {this.nullSeat("D17")}
              {this.renderSeat("D18")}
              {this.renderSeat("D19")}
              {this.renderSeat("D20")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.nullSeat("E2")}
              {this.nullSeat("E3")}
              {this.renderSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
              {this.nullSeat("E16")}
              {this.renderSeat("E17")}
              {this.renderSeat("E18")}
              {this.renderSeat("E19")}
              {this.renderSeat("E20")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.nullSeat("F2")}
              {this.nullSeat("F3")}
              {this.renderSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
              {this.nullSeat("F16")}
              {this.renderSeat("F17")}
              {this.renderSeat("F18")}
              {this.renderSeat("F19")}
              {this.renderSeat("F20")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.nullSeat("G2")}
              {this.nullSeat("G3")}
              {this.renderSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
              {this.nullSeat("G16")}
              {this.renderSeat("G17")}
              {this.renderSeat("G18")}
              {this.renderSeat("G19")}
              {this.renderSeat("G20")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.nullSeat("H2")}
              {this.nullSeat("H3")}
              {this.renderSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
              {this.nullSeat("H16")}
              {this.renderSeat("H17")}
              {this.renderSeat("H18")}
              {this.renderSeat("H19")}
              {this.renderSeat("H20")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.nullSeat("I2")}
              {this.nullSeat("I3")}
              {this.renderSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
              {this.nullSeat("I16")}
              {this.renderSeat("I17")}
              {this.renderSeat("I18")}
              {this.renderSeat("I19")}
              {this.renderSeat("I20")}
            </div>
            <div className="board-row">
              {this.nullSeat("J1")}
              {this.nullSeat("J2")}
              {this.nullSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
              {this.nullSeat("J16")}
              {this.renderSeat("J17")}
              {this.renderSeat("J18")}
              {this.renderSeat("J19")}
              {this.renderSeat("J20")}
            </div>
            <div className="board-row">
              {this.renderSeat("K1")}
              {this.renderSeat("K2")}
              {this.nullSeat("K3")}
              {this.renderSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.renderSeat("K14")}
              {this.renderSeat("K15")}
              {this.nullSeat("K16")}
              {this.renderSeat("K17")}
              {this.renderSeat("K18")}
              {this.renderSeat("K19")}
              {this.renderSeat("K20")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.nullSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
              {this.renderSeat("L15")}
              {this.nullSeat("L16")}
              {this.renderSeat("L17")}
              {this.renderSeat("L18")}
              {this.renderSeat("L19")}
              {this.renderSeat("L20")}
            </div>
            <div className="board-row">
              {this.renderSeat("M1")}
              {this.renderSeat("M2")}
              {this.nullSeat("M3")}
              {this.renderSeat("M4")}
              {this.renderSeat("M5")}
              {this.renderSeat("M6")}
              {this.renderSeat("M7")}
              {this.renderSeat("M8")}
              {this.renderSeat("M9")}
              {this.renderSeat("M10")}
              {this.renderSeat("M11")}
              {this.renderSeat("M12")}
              {this.renderSeat("M13")}
              {this.renderSeat("M14")}
              {this.renderSeat("M15")}
              {this.nullSeat("M16")}
              {this.renderSeat("M17")}
              {this.renderSeat("M18")}
              {this.renderSeat("M19")}
              {this.renderSeat("M20")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 2) {
      return (
        <div>
          <div className="screen">SCREEN2</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.nullSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.nullSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.nullSeat("D2")}
              {this.nullSeat("D3")}
              {this.nullSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.nullSeat("E2")}
              {this.nullSeat("E3")}
              {this.nullSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.nullSeat("F2")}
              {this.nullSeat("F3")}
              {this.nullSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.nullSeat("G2")}
              {this.nullSeat("G3")}
              {this.nullSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.nullSeat("H2")}
              {this.nullSeat("H3")}
              {this.nullSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
            </div>
            <div className="board-row">
              {this.renderSeat("I1")}
              {this.renderSeat("I2")}
              {this.nullSeat("I3")}
              {this.nullSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
            </div>
            <div className="board-row">
              {this.renderSeat("J1")}
              {this.renderSeat("J2")}
              {this.renderSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 3) {
      return (
        <div>
          <div className="screen">SCREEN3</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
              {this.renderSeat("A16")}
              {this.nullSeat("A17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.renderSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
              {this.renderSeat("B16")}
              {this.renderSeat("B17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.renderSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
              {this.renderSeat("C16")}
              {this.renderSeat("C17")}
              {this.nullSeat("C18")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.renderSeat("D2")}
              {this.renderSeat("D3")}
              {this.renderSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
              {this.nullSeat("D16")}
              {this.nullSeat("D17")}
              {this.nullSeat("D18")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.renderSeat("E2")}
              {this.renderSeat("E3")}
              {this.renderSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
              {this.nullSeat("E16")}
              {this.nullSeat("E17")}
              {this.nullSeat("E18")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.renderSeat("F2")}
              {this.renderSeat("F3")}
              {this.renderSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
              {this.nullSeat("F16")}
              {this.nullSeat("F17")}
              {this.nullSeat("F18")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.renderSeat("G2")}
              {this.renderSeat("G3")}
              {this.renderSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
              {this.nullSeat("G16")}
              {this.nullSeat("G17")}
              {this.nullSeat("G18")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.renderSeat("H2")}
              {this.renderSeat("H3")}
              {this.renderSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
              {this.nullSeat("H16")}
              {this.nullSeat("H17")}
              {this.nullSeat("H18")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.renderSeat("I2")}
              {this.renderSeat("I3")}
              {this.renderSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
              {this.nullSeat("I16")}
              {this.nullSeat("I17")}
              {this.nullSeat("I18")}
            </div>
            <div className="board-row">
              {this.nullSeat("J1")}
              {this.renderSeat("J2")}
              {this.renderSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
              {this.nullSeat("J16")}
              {this.nullSeat("J17")}
              {this.nullSeat("J18")}
            </div>
            <div className="board-row">
              {this.nullSeat("K1")}
              {this.renderSeat("K2")}
              {this.renderSeat("K3")}
              {this.renderSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.renderSeat("K14")}
              {this.renderSeat("K15")}
              {this.nullSeat("K16")}
              {this.renderSeat("K17")}
              {this.renderSeat("K18")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.renderSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
              {this.renderSeat("L15")}
              {this.renderSeat("L16")}
              {this.renderSeat("L17")}
              {this.renderSeat("L18")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 4) {
      return (
        <div>
          <div className="screen">SCREEN4</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
              {this.renderSeat("A16")}
              {this.nullSeat("A17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.renderSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
              {this.renderSeat("B16")}
              {this.renderSeat("B17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.renderSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
              {this.renderSeat("C16")}
              {this.renderSeat("C17")}
              {this.nullSeat("C18")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.renderSeat("D2")}
              {this.renderSeat("D3")}
              {this.renderSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
              {this.nullSeat("D16")}
              {this.nullSeat("D17")}
              {this.nullSeat("D18")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.renderSeat("E2")}
              {this.renderSeat("E3")}
              {this.renderSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
              {this.nullSeat("E16")}
              {this.nullSeat("E17")}
              {this.nullSeat("E18")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.renderSeat("F2")}
              {this.renderSeat("F3")}
              {this.renderSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
              {this.nullSeat("F16")}
              {this.nullSeat("F17")}
              {this.nullSeat("F18")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.renderSeat("G2")}
              {this.renderSeat("G3")}
              {this.renderSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
              {this.nullSeat("G16")}
              {this.nullSeat("G17")}
              {this.nullSeat("G18")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.renderSeat("H2")}
              {this.renderSeat("H3")}
              {this.renderSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
              {this.nullSeat("H16")}
              {this.nullSeat("H17")}
              {this.nullSeat("H18")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.renderSeat("I2")}
              {this.renderSeat("I3")}
              {this.renderSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
              {this.nullSeat("I16")}
              {this.nullSeat("I17")}
              {this.nullSeat("I18")}
            </div>
            <div className="board-row">
              {this.nullSeat("J1")}
              {this.renderSeat("J2")}
              {this.renderSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
              {this.nullSeat("J16")}
              {this.nullSeat("J17")}
              {this.nullSeat("J18")}
            </div>
            <div className="board-row">
              {this.nullSeat("K1")}
              {this.renderSeat("K2")}
              {this.renderSeat("K3")}
              {this.renderSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.renderSeat("K14")}
              {this.renderSeat("K15")}
              {this.nullSeat("K16")}
              {this.renderSeat("K17")}
              {this.renderSeat("K18")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.renderSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
              {this.renderSeat("L15")}
              {this.renderSeat("L16")}
              {this.renderSeat("L17")}
              {this.renderSeat("L18")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 5) {
      return (
        <div>
          <div className="screen">SCREEN5</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
              {this.renderSeat("A16")}
              {this.nullSeat("A17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.renderSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
              {this.renderSeat("B16")}
              {this.renderSeat("B17")}
              {this.nullSeat("B18")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.renderSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
              {this.renderSeat("C16")}
              {this.renderSeat("C17")}
              {this.nullSeat("C18")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.renderSeat("D2")}
              {this.renderSeat("D3")}
              {this.renderSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
              {this.nullSeat("D16")}
              {this.nullSeat("D17")}
              {this.nullSeat("D18")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.renderSeat("E2")}
              {this.renderSeat("E3")}
              {this.renderSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
              {this.nullSeat("E16")}
              {this.nullSeat("E17")}
              {this.nullSeat("E18")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.renderSeat("F2")}
              {this.renderSeat("F3")}
              {this.renderSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
              {this.nullSeat("F16")}
              {this.nullSeat("F17")}
              {this.nullSeat("F18")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.renderSeat("G2")}
              {this.renderSeat("G3")}
              {this.renderSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
              {this.nullSeat("G16")}
              {this.nullSeat("G17")}
              {this.nullSeat("G18")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.renderSeat("H2")}
              {this.renderSeat("H3")}
              {this.renderSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
              {this.nullSeat("H16")}
              {this.nullSeat("H17")}
              {this.nullSeat("H18")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.renderSeat("I2")}
              {this.renderSeat("I3")}
              {this.renderSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
              {this.nullSeat("I16")}
              {this.nullSeat("I17")}
              {this.nullSeat("I18")}
            </div>
            <div className="board-row">
              {this.nullSeat("J1")}
              {this.renderSeat("J2")}
              {this.renderSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
              {this.nullSeat("J16")}
              {this.nullSeat("J17")}
              {this.nullSeat("J18")}
            </div>
            <div className="board-row">
              {this.nullSeat("K1")}
              {this.renderSeat("K2")}
              {this.renderSeat("K3")}
              {this.renderSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.renderSeat("K14")}
              {this.renderSeat("K15")}
              {this.nullSeat("K16")}
              {this.renderSeat("K17")}
              {this.renderSeat("K18")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.renderSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
              {this.renderSeat("L15")}
              {this.renderSeat("L16")}
              {this.renderSeat("L17")}
              {this.renderSeat("L18")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 6) {
      return (
        <div>
          <div className="screen">SCREEN6</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.nullSeat("A3")}
              {this.nullSeat("A4")}
              {this.nullSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.renderSeat("A14")}
              {this.renderSeat("A15")}
              {this.nullSeat("A16")}
              {this.nullSeat("A17")}
              {this.nullSeat("A18")}
              {this.nullSeat("A19")}
              {this.nullSeat("A20")}
            </div>
            <div className="board-row">
              {this.renderSeat("B1")}
              {this.renderSeat("B2")}
              {this.renderSeat("B3")}
              {this.nullSeat("B4")}
              {this.nullSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.renderSeat("B14")}
              {this.renderSeat("B15")}
              {this.nullSeat("B16")}
              {this.nullSeat("B17")}
              {this.renderSeat("B18")}
              {this.renderSeat("B19")}
              {this.renderSeat("B20")}
            </div>
            <div className="board-row">
              {this.renderSeat("C1")}
              {this.renderSeat("C2")}
              {this.renderSeat("C3")}
              {this.nullSeat("C4")}
              {this.nullSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.renderSeat("C14")}
              {this.renderSeat("C15")}
              {this.nullSeat("C16")}
              {this.nullSeat("C17")}
              {this.renderSeat("C18")}
              {this.renderSeat("C19")}
              {this.renderSeat("C20")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.nullSeat("D2")}
              {this.nullSeat("D3")}
              {this.renderSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.renderSeat("D14")}
              {this.renderSeat("D15")}
              {this.renderSeat("D16")}
              {this.renderSeat("D17")}
              {this.nullSeat("D18")}
              {this.nullSeat("D19")}
              {this.nullSeat("D20")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.nullSeat("E2")}
              {this.nullSeat("E3")}
              {this.renderSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.renderSeat("E14")}
              {this.renderSeat("E15")}
              {this.renderSeat("E16")}
              {this.renderSeat("E17")}
              {this.nullSeat("E18")}
              {this.nullSeat("E19")}
              {this.nullSeat("E20")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.nullSeat("F2")}
              {this.nullSeat("F3")}
              {this.renderSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.renderSeat("F14")}
              {this.renderSeat("F15")}
              {this.renderSeat("F16")}
              {this.renderSeat("F17")}
              {this.nullSeat("F18")}
              {this.nullSeat("F19")}
              {this.nullSeat("F20")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.nullSeat("G2")}
              {this.nullSeat("G3")}
              {this.renderSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.renderSeat("G14")}
              {this.renderSeat("G15")}
              {this.renderSeat("G16")}
              {this.renderSeat("G17")}
              {this.nullSeat("G18")}
              {this.nullSeat("G19")}
              {this.nullSeat("G20")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.nullSeat("H2")}
              {this.nullSeat("H3")}
              {this.renderSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.renderSeat("H14")}
              {this.renderSeat("H15")}
              {this.renderSeat("H16")}
              {this.renderSeat("H17")}
              {this.nullSeat("H18")}
              {this.nullSeat("H19")}
              {this.nullSeat("H20")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.nullSeat("I2")}
              {this.nullSeat("I3")}
              {this.renderSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.renderSeat("I14")}
              {this.renderSeat("I15")}
              {this.renderSeat("I16")}
              {this.renderSeat("I17")}
              {this.nullSeat("I18")}
              {this.nullSeat("I19")}
              {this.nullSeat("I20")}
            </div>
            <div className="board-row">
              {this.renderSeat("J1")}
              {this.renderSeat("J2")}
              {this.nullSeat("J3")}
              {this.renderSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.renderSeat("J14")}
              {this.renderSeat("J15")}
              {this.renderSeat("J16")}
              {this.renderSeat("J17")}
              {this.nullSeat("J18")}
              {this.renderSeat("J19")}
              {this.renderSeat("J20")}
            </div>
            <div className="board-row">
              {this.renderSeat("K1")}
              {this.renderSeat("K2")}
              {this.renderSeat("K3")}
              {this.renderSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.renderSeat("K14")}
              {this.renderSeat("K15")}
              {this.renderSeat("K16")}
              {this.renderSeat("K17")}
              {this.renderSeat("K18")}
              {this.renderSeat("K19")}
              {this.renderSeat("K20")}
            </div>
          </div>
        </div>
      );
    } else if (this.props.screen == 7) {
      return (
        <div>
          <div className="screen">SCREEN7</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.nullSeat("A14")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.nullSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.nullSeat("B14")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.nullSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.nullSeat("C14")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.nullSeat("D2")}
              {this.nullSeat("D3")}
              {this.nullSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.nullSeat("D14")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.nullSeat("E2")}
              {this.nullSeat("E3")}
              {this.nullSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.nullSeat("E14")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.nullSeat("F2")}
              {this.nullSeat("F3")}
              {this.nullSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.nullSeat("F14")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.nullSeat("G2")}
              {this.nullSeat("G3")}
              {this.nullSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.nullSeat("G14")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.nullSeat("H2")}
              {this.nullSeat("H3")}
              {this.nullSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.nullSeat("H14")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.nullSeat("I2")}
              {this.nullSeat("I3")}
              {this.nullSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.nullSeat("I14")}
            </div>
            <div className="board-row">
              {this.renderSeat("J1")}
              {this.renderSeat("J2")}
              {this.nullSeat("J3")}
              {this.nullSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.nullSeat("J14")}
            </div>
            <div className="board-row">
              {this.renderSeat("K1")}
              {this.renderSeat("K2")}
              {this.nullSeat("K3")}
              {this.nullSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.nullSeat("K14")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.renderSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
            </div>
          </div>
        </div>
      );
    } else {
      return (
        <div>
          <div className="screen">SCREEN8</div>
          <div style={{margin:'auto',width:'50%'}}>
            <div className="board-row">
              {this.nullSeat("A1")}
              {this.nullSeat("A2")}
              {this.renderSeat("A3")}
              {this.renderSeat("A4")}
              {this.renderSeat("A5")}
              {this.renderSeat("A6")}
              {this.renderSeat("A7")}
              {this.renderSeat("A8")}
              {this.renderSeat("A9")}
              {this.renderSeat("A10")}
              {this.renderSeat("A11")}
              {this.renderSeat("A12")}
              {this.renderSeat("A13")}
              {this.nullSeat("A14")}
            </div>
            <div className="board-row">
              {this.nullSeat("B1")}
              {this.nullSeat("B2")}
              {this.renderSeat("B3")}
              {this.renderSeat("B4")}
              {this.renderSeat("B5")}
              {this.renderSeat("B6")}
              {this.renderSeat("B7")}
              {this.renderSeat("B8")}
              {this.renderSeat("B9")}
              {this.renderSeat("B10")}
              {this.renderSeat("B11")}
              {this.renderSeat("B12")}
              {this.renderSeat("B13")}
              {this.nullSeat("B14")}
            </div>
            <div className="board-row">
              {this.nullSeat("C1")}
              {this.nullSeat("C2")}
              {this.renderSeat("C3")}
              {this.renderSeat("C4")}
              {this.renderSeat("C5")}
              {this.renderSeat("C6")}
              {this.renderSeat("C7")}
              {this.renderSeat("C8")}
              {this.renderSeat("C9")}
              {this.renderSeat("C10")}
              {this.renderSeat("C11")}
              {this.renderSeat("C12")}
              {this.renderSeat("C13")}
              {this.nullSeat("C14")}
            </div>
            <div className="board-row">
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
              {this.nullSeat("X")}
            </div>
            <div className="board-row">
              {this.nullSeat("D1")}
              {this.nullSeat("D2")}
              {this.nullSeat("D3")}
              {this.nullSeat("D4")}
              {this.renderSeat("D5")}
              {this.renderSeat("D6")}
              {this.renderSeat("D7")}
              {this.renderSeat("D8")}
              {this.renderSeat("D9")}
              {this.renderSeat("D10")}
              {this.renderSeat("D11")}
              {this.renderSeat("D12")}
              {this.renderSeat("D13")}
              {this.nullSeat("D14")}
            </div>
            <div className="board-row">
              {this.nullSeat("E1")}
              {this.nullSeat("E2")}
              {this.nullSeat("E3")}
              {this.nullSeat("E4")}
              {this.renderSeat("E5")}
              {this.renderSeat("E6")}
              {this.renderSeat("E7")}
              {this.renderSeat("E8")}
              {this.renderSeat("E9")}
              {this.renderSeat("E10")}
              {this.renderSeat("E11")}
              {this.renderSeat("E12")}
              {this.renderSeat("E13")}
              {this.nullSeat("E14")}
            </div>
            <div className="board-row">
              {this.nullSeat("F1")}
              {this.nullSeat("F2")}
              {this.nullSeat("F3")}
              {this.nullSeat("F4")}
              {this.renderSeat("F5")}
              {this.renderSeat("F6")}
              {this.renderSeat("F7")}
              {this.renderSeat("F8")}
              {this.renderSeat("F9")}
              {this.renderSeat("F10")}
              {this.renderSeat("F11")}
              {this.renderSeat("F12")}
              {this.renderSeat("F13")}
              {this.nullSeat("F14")}
            </div>
            <div className="board-row">
              {this.nullSeat("G1")}
              {this.nullSeat("G2")}
              {this.nullSeat("G3")}
              {this.nullSeat("G4")}
              {this.renderSeat("G5")}
              {this.renderSeat("G6")}
              {this.renderSeat("G7")}
              {this.renderSeat("G8")}
              {this.renderSeat("G9")}
              {this.renderSeat("G10")}
              {this.renderSeat("G11")}
              {this.renderSeat("G12")}
              {this.renderSeat("G13")}
              {this.nullSeat("G14")}
            </div>
            <div className="board-row">
              {this.nullSeat("H1")}
              {this.nullSeat("H2")}
              {this.nullSeat("H3")}
              {this.nullSeat("H4")}
              {this.renderSeat("H5")}
              {this.renderSeat("H6")}
              {this.renderSeat("H7")}
              {this.renderSeat("H8")}
              {this.renderSeat("H9")}
              {this.renderSeat("H10")}
              {this.renderSeat("H11")}
              {this.renderSeat("H12")}
              {this.renderSeat("H13")}
              {this.nullSeat("H14")}
            </div>
            <div className="board-row">
              {this.nullSeat("I1")}
              {this.nullSeat("I2")}
              {this.nullSeat("I3")}
              {this.nullSeat("I4")}
              {this.renderSeat("I5")}
              {this.renderSeat("I6")}
              {this.renderSeat("I7")}
              {this.renderSeat("I8")}
              {this.renderSeat("I9")}
              {this.renderSeat("I10")}
              {this.renderSeat("I11")}
              {this.renderSeat("I12")}
              {this.renderSeat("I13")}
              {this.nullSeat("I14")}
            </div>
            <div className="board-row">
              {this.renderSeat("J1")}
              {this.renderSeat("J2")}
              {this.nullSeat("J3")}
              {this.nullSeat("J4")}
              {this.renderSeat("J5")}
              {this.renderSeat("J6")}
              {this.renderSeat("J7")}
              {this.renderSeat("J8")}
              {this.renderSeat("J9")}
              {this.renderSeat("J10")}
              {this.renderSeat("J11")}
              {this.renderSeat("J12")}
              {this.renderSeat("J13")}
              {this.nullSeat("J14")}
            </div>
            <div className="board-row">
              {this.renderSeat("K1")}
              {this.renderSeat("K2")}
              {this.nullSeat("K3")}
              {this.nullSeat("K4")}
              {this.renderSeat("K5")}
              {this.renderSeat("K6")}
              {this.renderSeat("K7")}
              {this.renderSeat("K8")}
              {this.renderSeat("K9")}
              {this.renderSeat("K10")}
              {this.renderSeat("K11")}
              {this.renderSeat("K12")}
              {this.renderSeat("K13")}
              {this.nullSeat("K14")}
            </div>
            <div className="board-row">
              {this.renderSeat("L1")}
              {this.renderSeat("L2")}
              {this.renderSeat("L3")}
              {this.renderSeat("L4")}
              {this.renderSeat("L5")}
              {this.renderSeat("L6")}
              {this.renderSeat("L7")}
              {this.renderSeat("L8")}
              {this.renderSeat("L9")}
              {this.renderSeat("L10")}
              {this.renderSeat("L11")}
              {this.renderSeat("L12")}
              {this.renderSeat("L13")}
              {this.renderSeat("L14")}
            </div>
          </div>
        </div>
      );
    } 
  }
}

class Seat extends React.Component {

  render() {
    return (
      <button
        className="seat"
        onClick={() => this.props.onClick()}
        style={{background: this.props.color}}
      >
        {this.props.number}
      </button>
    );
  }
}